name: Arduino Lint
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v2.0.0
        with:
          compliance: strict
          library-manager: update
